### ISSUE TITLE
PE verification error

### ISSUE THREAD

**Issue by marcells** [vescon/MethodBoundaryAspect.Fody#10]
The verification of the following method fails, when it is compiled with the 'optimize code' compilation flag:
See the comment in the code sample.
```csharp
[DisplayWaitCursor]
private void Print_Click(object sender, RoutedEventArgs e)
{
    if (!FromDatePicker.SelectedDate.HasValue || !ToDatePicker.SelectedDate.HasValue)
        return;

    _ganttChartViewModel.VisibleRange = new DateSpan(
        FromDatePicker.SelectedDate.Value,
        ToDatePicker.SelectedDate.Value);

    SomeMethod();  // When the comment is removed it still fails

    var window = new ContainerWindow
                    {
                        Child = new PrintPreviewDialog { Document = CreatePrintDocument() },
                        Title = LangResources._Preview
                    };

    window.Show();
}

private void SomeMethod()
{
     // this method is really empty
}
```

PE verification error:
`Vescon.Biquanda.Client.Presentation.Toolkit.MasterData.AbstractDialog::TabControl_SelectionChanged][offset 0x00000095] jmp / exception into the middle of an instruction.(Error: 0x80131847)`

**Comment by Ralf1108** [comment]
cannot reproduce.
Please try yourself via unittest: "IfStrangeMethodForIssue10_ThenTheAssemblyShouldBeValid"

**Comment by Ralf1108** [comment]
try using latest method boundary aspect

**Comment by marcells** [comment]
The code does not exist anymore. So, no issues now. :-D
