### ISSUE TITLE
v2.0.148 nuget publish failed

### ISSUE THREAD

**Issue by psaxton** [vescon/MethodBoundaryAspect.Fody#103]
The nuget publish for version 2.0.148 failed due to [expired or incorrect api key](https://github.com/vescon/MethodBoundaryAspect.Fody/actions/runs/3411259851/jobs/5675240326#step:11:43). 

Expected result: The package gets published to NuGet.

**Comment by psaxton** [comment]
@Ralf1108 I'm hoping you have access to update the nuget api key.

**Comment by Ralf1108** [comment]
HI @psaxton,

I am working on it since the release but the access to the api key is by my former company. I am in contact with them and they try to help me out. Keep the fingers crossed ;-)

**Comment by marcells** [comment]
Hi @psaxton and @Ralf1108,

a new api key is assigned now. There shouldn't be any issues in at least the next 365 days. 🙂

I did also re-run the failed build.
