### ISSUE TITLE
How to access ILogger 'injected' property to 'log' on exception?

### ISSUE THREAD

**Issue by jeffward01** [vescon/MethodBoundaryAspect.Fody#109]
Hello!

My goal is this:

I want to emulate this:

```csharp

private readonly ILogger _logger;

   public SomeClass(ILogger logger)
  {
  _logger = logger;
  }

    /// <inheritdoc />
    async Task<double> IAeonicCanAverage<TEntity>.AverageAsync(
        Expression<Func<TEntity, long?>> selector,
        CancellationToken cancellationToken)
    {
        try
        {
            return await this._innerRepository.AverageAsync(selector, cancellationToken);
        }
        catch (Exception ex)
        {
            
           // I am having issues resolving '_logger'
          // LogErrorOccurredForOperation => Is just an extension method 
            this._logger.LogErrorOccurredForOperation("average", typeof(TEntity).Name, ex);

            throw;
        }
    }

```

Is it possible to access the `ILogger` type? I don't see any examples or other issues that attempt to access a DI resolved type like this.

Thanks

**Comment by Ralf1108** [comment]
If I understand you correct you want to inject a service into an aspect?

As the aspect scope is the weaved method there is no direct solution to this.
What works in every case would be a static global service locater which is accessed inside the aspect class.

More tricky solution would be to have the contract that a specific argument of the method call is used for the required service but this wouldn't have any compiler safety support and could lead to bad maintenance

**Comment by Ralf1108** [comment]
checkout this documentation from PostSharp:
[https://doc.postsharp.net/global-service-locator](https://doc.postsharp.net/global-service-locator)

**Comment by jeffward01** [comment]
> If I understand you correct you want to inject a service into an aspect?

Yes thats correct

> More tricky solution would be to have the contract that a specific argument of the method call is used for the required service but this wouldn't have any compiler safety support and could lead to bad maintenance

Ah that makes sense, I was trying to avoid boiler plate code with Fody, and don't want to create more work for myself.

> If you check the documentation on the left side of the page there additional possibilities for DI into aspects.
But as MBA is not as sophisticated as PostSharp not all possibilites applies to MBA.

Thanks for this link! Thats very cool! The world of Fody is amazing, its a powerful tool, Im still learning how to apply it selectively so its useful and the results are predictable

Thanks so much!

**Comment by douglasg14b** [comment]
Hm, this is problematic when you only care about services that are scoped 🤔
