### ISSUE TITLE
Support net45

### ISSUE THREAD

**Issue by maulwuff** [vescon/MethodBoundaryAspect.Fody#13]
Would it be possible to add net45 to the supported frameworks? 
Currently only net461 is set, this would prevent using this package in my environment.
(while supporting netstandard2.0 is great ;-D )

**Comment by marcells** [comment]
Could you try this and make a PR? Otherwise it could take a while until I find some time to investigate this issue.

**Comment by maulwuff** [comment]
Found out that net461 supports referencing netstandard2.0 projects directly. This makes it possible to use netstandard2.0 dlls in net461 projects directly (no need to have 2 dlls for the same project anymore :-D )
There is also no reason to stick with net45 / net452 with repsect to the .net version which ships with win7 - in my case.

**Comment by marcells** [comment]
Alright. Thanks for the info. 😉
