### ISSUE TITLE
unhandled exception with ctor params

### ISSUE THREAD

**Issue by maulwuff** [vescon/MethodBoundaryAspect.Fody#14]
I try to add params to the ctor, like `MyAspect(params string[] vals)`

 but this results in:

```
Fody: Fody (version 1.0.0.0) Executing
MSBUILD : error : Fody: An unhandled exception occurred:
MSBUILD : error : Exception:
MSBUILD : error : Parametertype: System.String[]
 StackTrace:
    at MethodBoundaryAspect.Fody.InstructionBlockCreator.LoadValueOnStack(TypeReference parameterType, Object value, ModuleDefinition module)
    at MethodBoundaryAspect.Fody.InstructionBlockCreator.NewObject(VariableDefinition newInstance, TypeReference instanceTypeReference, ModuleDefinition module, CustomAttribute aspect, Int32 aspectCounter)
    at MethodBoundaryAspect.Fody.InstructionBlockChainCreator.CreateAspectInstance(CustomAttribute aspect)
    at MethodBoundaryAspect.Fody.MethodWeaver.Weave(MethodDefinition method, CustomAttribute aspect, AspectMethods overriddenAspectMethods, ModuleDefinition moduleDefinition)

```

I also tried to leave the ctor alone and to it like this, with a property in the attribute:
```
[MyAspect(Foo = new[] { nameof(Bar), nameof(Baz) })]
```

but this throws the same unhandled exception.

**Comment by maulwuff** [comment]
some test code. as soon as there is one override, the exception is thrown

```
 public class Test
    {

        [MyAspect(Foo = new[] { "a", "b" })]
        public string TestMethod()
        {
            return null;
        }


    }
    public class MyAspect : OnMethodBoundaryAspect
    {
        public override void OnEntry(MethodExecutionArgs args)
        {//makes it fail
        }

        public override void OnExit(MethodExecutionArgs args)
        {//makes it fail
        }

        public string[] Foo
        {
            get; set;
        }
    }
```

**Comment by marcells** [comment]
@ralf1108 Any idea about that?

**Comment by maulwuff** [comment]
I think it has to do with https://github.com/vescon/MethodBoundaryAspect.Fody/issues/4#issuecomment-179808020  where you mention which types are allowed for attributes. 
As far as I can tell, `array` is the only kind of param which is not yet supported and thus throws a `NotSupportedException`

**Comment by maulwuff** [comment]
I worked around this, by creating various ctors with different numbers of arguments. The array is created afterwards inside the class ;-)

**Comment by marcells** [comment]
@maulwuff Please check https://www.nuget.org/packages/MethodBoundaryAspect.Fody/1.0.16.

**Comment by maulwuff** [comment]
Whoops, 1.0.16 breaks existing code!  I don't even get to the place to weave the above posted repro :-(
1.014 still weaves as expected, but not for the repro in this ticket.

So 1.0.16 doesn't fix this ticket, but also breaks existing code which works in 1.0.14

**Comment by marcells** [comment]
Could you try setting it as a constructor parameter, instead of a property?

**Comment by maulwuff** [comment]
let's first fix #23 and then come back to this one.

**Comment by keith-anders** [comment]
The following compiles without issue using 1.0.16 in either .net Framework or .net Standard.

```csharp
public class TestClass
{
  [TriggerPropChanged("a")]
  public string TestProp { get; set; }
}

public class TriggerPropChangedAttribute : OnMethodBoundaryAspect
{
  public TriggerPropChangedAttribute(string alsoNotify) { }

  public override void OnEntry(MethodExecutionArgs arg) => base.OnEntry(arg);
  public override void OnException(MethodExecutionArgs arg) => base.OnException(arg);
  public override void OnExit(MethodExecutionArgs arg) => base.OnExit(arg);
}

@maulwuff  Can you help clarify what I am missing in order to set up a reproducible example of your issue?

**Comment by maulwuff** [comment]
@keith-anders please see the sample project in #24

**Comment by Ralf1108** [comment]
@maulwuff  can you retest your issue with v1.0.39?

**Comment by maulwuff** [comment]
works really nice.
I just had to replace the ctor of the attribute with a `params string[]` property, and all existing code compiled fine.
I also really like, that no Mono dlls show up in the output folder anymore ;-)

**Comment by maulwuff** [comment]
tested wit 1.0.41
