### ISSUE TITLE
Add support for linked weaver files

### ISSUE THREAD

**Issue by Wautvda** [vescon/MethodBoundaryAspect.Fody#15]
When using a linked weaver file (FodyWeaver.xml), this isn't recognised at buildtime (with the error Fody: Could not find path to weavers file).
The files is added as a link with the following code:
`
<ItemGroup>
    <Content Include="..\..\..\Resources\Config\FodyWeavers.xml">
      <Link>FodyWeavers.xml</Link>
    </Content>
  </ItemGroup>
`

This would be easier to use since all the weaver files will contain the same extensions (for now).

**Comment by marcells** [comment]
That feature must be supported by https://github.com/Fody/Fody. The MethodBoundaryAspect is just a plugin for it. So please post this issue there.

**Comment by marcells** [comment]
@Wautvda That issue looks like your proposal: https://github.com/Fody/Fody/issues/501

**Comment by Wautvda** [comment]
Sorry, indeed used the wrong repo to post in.
And thanks. Created the same kind of workaround for the moment as well :)
