### ISSUE TITLE
The weaver needs to update to at least version 3.0 of FodyHelpers

### ISSUE THREAD

**Issue by dev-anton** [vescon/MethodBoundaryAspect.Fody#16]
Following exception occurred after the update on Fody 3.0.1:

Fody: The weaver assembly 'MethodBoundaryAspect.Fody, Version=1.0.7.0, Culture=neutral, PublicKeyToken=296379d5065c9d61' references an out of date version of Mono.Cecil.dll. Expected strong name token of '1C-A0-91-87-7D-12-CA-03' but got '50-CE-BF-1C-CE-B9-D0-5E'. The weaver needs to update to at least version 3.0 of FodyHelpers.

**Comment by Ralf1108** [comment]
yes, i will look into this !

**Comment by Ralf1108** [comment]
please try version 1.0.8

**Comment by Ralf1108** [comment]
please use 1.0.12
There were some issues with Fody 3.0.1 required usage of base class BaseModuleWeaver

**Comment by dev-anton** [comment]
Thank you! It's ok.

**Comment by Ralf1108** [comment]
glad to hear that it works ;-)
