### ISSUE TITLE
Mark Fody as development dependency

### ISSUE THREAD

**Issue by maulwuff** [vescon/MethodBoundaryAspect.Fody#18]
I am having a hard time to create a nuget package with only MethodBoundaryAspect.dll as a neccessary reference. It always pulls Fody with it. 
I've seen, that MethodBoundaryAspect.Fody.nuspec has development dependency set to true. This is not true. MethodBoundaryAspect.dll is needed throughout the system. Only Fody and FodyCecil can be left aside. Can you please mark Fody and FodyCecil as development dependencies? 

Right now, my nuget will have a reference on MethodBoundaryAspect package which itself has a reference on Fody. 
This has the effect, that even the top level exe project will search for FodyWeavers and pull everything in it finds in the reference tree.

**Comment by Ralf1108** [comment]
never heard of "development dependency" before.. so I will have to investigate this first

**Comment by Ralf1108** [comment]
do you mind make the required change and provide a pull request? :-)

**Comment by damageboy** [comment]
I think he means that the MethodBoundayAspect.csproj should contain the package references as explained in the basicfodyaddin README.md:

https://github.com/Fody/BasicFodyAddin/blob/9e28d1dd2b89bc77588f510dfe7174b5623b13ee/BasicFodyAddin/BasicFodyAddin.csproj#L11

**Comment by Ralf1108** [comment]
we try to separate the weaver stuff and the OnMethodBoundary base class into separate assemblies. Then we could remove the dependency to fody for the latter one.

**Comment by maulwuff** [comment]
Um, there is no dependency on Fody or Cecil from MethodBoundaryAspect.dll - that is fine.

I think it is enough to modify the nuget package spec like shown in comment by damageboy.
There is also a spec page on this at  https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html

**Comment by marcells** [comment]
We also want to use a lower Target Framework (e.g. 4.5.2) for our base class. That is only possible by separating the base class and runtime attributes from the weaving code. The weaving code is dependent on FodyCecil, why it has to be at lease 4.6.

**Comment by maulwuff** [comment]
ah ok, fair enough ;)
I had to go back to v0.35 to get .net4.5.2 support on a project where I was not able to set .net 4.6.2 as the base because of contract stuff

**Comment by marcells** [comment]
I made released a new version (1.0.41) right now. It should be possible to use the aspect under .NET 4.5.1. I did also mark the packages a developmentDependency.

Could you check, if it is working for you?
