### ISSUE TITLE
Cannot debug weaved method

### ISSUE THREAD

**Issue by dev-anton** [vescon/MethodBoundaryAspect.Fody#21]
The problem experienced after the [reimplemented weaver](https://github.com/vescon/MethodBoundaryAspect.Fody/tree/7dee9b49964fc6f82c3d2567375d80267b91338e) changes

I used skipped test "IfWeavedTestProgramIsExecuted_ThenTheDebugSymbolsShouldWorkAndTheDebuggerShouldBeAttachable" for checking up: breakpoint into TestClass.DoIt is never hitting.

**Comment by dev-anton** [comment]
I created an issue to know your opinion - possible it’s Fody or Mono issue. As I understood no. I will research further.

**Comment by Ralf1108** [comment]
your pull request solved this issue 👍 
thx for contributing

**Comment by Ralf1108** [comment]
fixed in nuget package 1.0.14
