### ISSUE TITLE
Can not add arguments to OnMethodBoundaryAspect attribute

### ISSUE THREAD

**Issue by swestner** [vescon/MethodBoundaryAspect.Fody#4]
If I try and add an initializer or constructor parameters to an OnMethodBoundaryAspect derived attribute, the attribute breaks the build. 

For example, given something like : 

```
[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    public class ExceptionAttribute : OnMethodBoundaryAspect
    {
        public Type ExceptionType { get; set; }
        public string TranslationKey { get; set; }
    }

```

If I try and decorate a method like this :

```
[ExceptionAttribute(TranslationKey = "fun")]
public void Method()

```

The build fails with this stack :

```
1>------ Build started: Project: MethodBoundaryAspect.Tests, Configuration: Debug Any CPU ------
1>    Fody: Fody (version 1.29.2.0) Executing
1>MSBUILD : error : Fody: An unhandled exception occurred:
1>MSBUILD : error : Exception:
1>MSBUILD : error : Parametertype: System.String
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    at MethodBoundaryAspect.Fody.InstructionBlockCreator.LoadConstOnStack(TypeReference parameterType, Object value)
1>MSBUILD : error :    at MethodBoundaryAspect.Fody.InstructionBlockCreator.NewObject(VariableDefinition newInstance, TypeReference instanceTypeReference, ModuleDefinition module, CustomAttribute aspect, Int32 aspectCounter)
1>MSBUILD : error :    at MethodBoundaryAspect.Fody.InstructionBlockChainCreator.CreateAspectInstance(CustomAttribute aspect)
1>MSBUILD : error :    at MethodBoundaryAspect.Fody.MethodWeaver.Weave(MethodDefinition method, CustomAttribute aspect, AspectMethods overriddenAspectMethods, ModuleDefinition moduleDefinition)
1>MSBUILD : error :    at MethodBoundaryAspect.Fody.ModuleWeaver.Execute(ModuleDefinition module)
1>MSBUILD : error :    at lambda_method(Closure , Object )
1>MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 164
1>MSBUILD : error :    at InnerWeaver.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 82
1>MSBUILD : error : Source:
1>MSBUILD : error : MethodBoundaryAspect.Fody
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : Mono.Cecil.Cil.Instruction LoadConstOnStack(Mono.Cecil.TypeReference, System.Object)
1>MSBUILD : error : 
1>    Fody:   Finished Fody 416ms.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

```

If I clone the repo and try and reproduce the error from within the repos unit tests, I can not, everything works fine. 

Here is a repo that reproduces the issue 

https://github.com/swestner/MethodBoundaryAspect.Test

Any ideas? I am happy to help, but I would need some direction.

**Comment by swestner** [comment]
I can see now this is an issue with reference types. The `LoadConstOnStack` only handles primitives and value types. When I tested it in the repos unit tests, i tested using an int, so it didn't fail. 

Oddly it seems like it should handle string but does not. 

What would be involved in adding reference types to the handled const's? 

I'm new to this, so I might be off, but looking at other projects that do something similar, it would require multiple instructions which the current implementation doesn't handle. Is this the reason they were left out?

**Comment by marcells** [comment]
We just didn't need it for our project. Feel free to get it work with strings or other possible types. If you get it working then simply send a pull request with the code changes/tests and we'll merge it.

According to the [MSDN](https://msdn.microsoft.com/en-us/library/aa288454(v=vs.71).aspx) the possible attribute values are restricted to:
- Simple types (bool, byte, char, short, int, long, float, and double)
- string
- System.Type
- enums
- object (The argument to an attribute parameter of type object must be a constant value of one of the above types.)
- One-dimensional arrays of any of the above types

**Comment by swestner** [comment]
Good to know about attribute type restrictions, thanks for the heads up.

Do you have any idea how to put Type on the stack? 

String was trivial, it just required rearranging the existing logic. But I am not sure what opcode to use for Type, or if it more complex than using a single instruction.

**Comment by marcells** [comment]
I'd try to make a simple sample and decompile it with [ILSpy](http://ilspy.net/). Then you should see what opcodes are needed, i think.

**Comment by swestner** [comment]
Unfortunately the IL has nothing to indicate what is being pushed. I am currently looking for an alternative.

Also, would you except a PR that ignores unhandled types instead of throwing an exception? This would allow the user to manually handle anything the decorator does not. 

For example, in the OnEntry method, a user could get the instance attached to the args, and manually resolve anything the compiler doesn't.

**Comment by Ralf1108** [comment]
should work now with "Type" and "string" attribute ctor parameters

**Comment by swestner** [comment]
your awesome!!

**Comment by swestner** [comment]
Also, if you feel like posting an answer on stack, here is the question : http://stackoverflow.com/questions/35215430/create-an-instruction-for-type
