### ISSUE TITLE
MethodBoundaryAspect library necessarily depends on NetStandard.Library

### ISSUE THREAD

**Issue by adimosh** [vescon/MethodBoundaryAspect.Fody#41]
Importing MethodBoundaryAspect forces the library that it is imported in to depend on NetStandard.Library. Also, it only allows for .NET 4.5.2 or above and .NET Standard 2.0.

If the NetStandard.Library package is not imported, then the following error occurs:

> Error	CS0012 The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

Such a limitation could easily be fixed in the library by explicitly stating its dependencies.

Since Fody itself can use PrivateAssets="all", it would be trivial to offer MethodBoundaryAspect as a completely separate NuGet package which will support any framework version and standard, as there is no reason for a .NET Standard 2.0 limitation. Such a package would, then, be used by MethodBoundaryAspect.Fody, which is the actual weaver.

With this, the weaver is completely disconnected from the metadata package, and two problems are solved:
1. All possible targets are supported
2. The runtime dependency issue on the weaver package itself is fixed

**Comment by adimosh** [comment]
Forking this in order to develop a fix and a pull request ASAP.

**Comment by marcells** [comment]
It's already separated. It could be possible to target an older framework in porject `MethodBoundaryAspect.csproj`.

Attributes (needed during runtime, cause implemented aspects depend on it): https://github.com/vescon/MethodBoundaryAspect.Fody/tree/master/MethodBoundaryAspect

Weaver (needed during compile time for weaving):
https://github.com/vescon/MethodBoundaryAspect.Fody/tree/master/MethodBoundaryAspect.Fody

**Comment by adimosh** [comment]
The problem that I'm identifying is that, although the weaver is a compile-time dependency, the attributes are not. If they are contained within the same NuGet package, then the minimum target frameworks are the one imposed by the NuGet package. Even though the attributes would work just fine targeting .NET Standard 1.3, for example, the target project must be .NET Standard 2.0.

Also, the target project must have a dependency on .NET Standard library, even though one is not needed or desired.

**Comment by Martinay** [comment]
Referencing only the needed packages instead of the NETStandard.Library is not the current approach anymore. This has changed [dotnet faq](https://github.com/dotnet/standard/blob/master/docs/faq.md#should-i-reference-the-meta-package-or-should-i-reference-individual-packages).
With commit 9d1a77a the needed version is changed to .netstandard 1.0, therefore I think everything from this issue is solved and I can close it. If not, please reopen it or create a new one.
