### ISSUE TITLE
MethodBoundaryAspect cannot be used in dotnet standard with default NuGet restore

### ISSUE THREAD

**Issue by clawrenceks** [vescon/MethodBoundaryAspect.Fody#47]
The behaviour I am describing below is something that I have seen in both .net core 2.0 applications and .net standard 2.0 class libraries.

When installing the MethodBoundaryAspect.Fody package, from the UI or command line tools, the library is not immediately usable without manual package configuration. This is demonstrated below. I can not see any documentation regarding this anywhere, is this intended behaviour? Or does the 'fix' described below have any undesired side effect?

After installing the NuGet package the entry in .csproj will look as follows:

    <PackageReference Include="MethodBoundaryAspect.Fody" Version="1.0.66">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>

With the package configured as follows, the library is unusable as it is not detected by the compiler - see screenshot below.

![image](https://user-images.githubusercontent.com/26073240/45508538-74936300-b76b-11e8-9b6d-853465ea6bff.png)

To resolve the issue I change the csproj package reference to the following and all works again.

    <PackageReference Include="MethodBoundaryAspect.Fody" Version="1.0.66" />

**Comment by cpwood** [comment]
Same here, but hat tip to @clawrenceks for the workaround!

**Comment by mfe-** [comment]
This should be added to the install guid! Thanks

**Comment by marcells** [comment]
Uh, thanks for the information. :+1: We will investigate that issue. If you have a solution for it (beside documentation) let us know it.

**Comment by Martinay** [comment]
should be fixed with version 2.0.104. If the issue still occures please reopen this bug or create a new one.
