### ISSUE TITLE
Support for modification of ref parameters in the "OnEntry" override

### ISSUE THREAD

**Issue by patrickcdsouza** [vescon/MethodBoundaryAspect.Fody#49]
It would be nice if **ref** parameters to a method could be changed as supported in the [PostSharp On­Method­Boundary­Aspect](http://doc.postsharp.net/t_postsharp_aspects_onmethodboundaryaspect) 

A screenshot of the relevant section from the link above is as seen below
 ![image](https://user-images.githubusercontent.com/20051643/46402602-19b0b400-c6f8-11e8-9c77-294165a9edad.png)

Basically the functionality that I am looking for is as follows:

> Every method that has a _User_ type will be decorated with a _DefaultUserAspect_. This aspect will have an _OnEntry_ override that searches through the argument list for a argument of type _User_. If the _User_ parameter is found to be _null_, then the parameter will be replaced with the _default user_.

I have created a VS2017 project with the test cases helps indicate the behaviour that I am looking for in this extension. Please find it as attached below
[MethodBoundaryAspect.Fody.Issue.Repro.zip](https://github.com/vescon/MethodBoundaryAspect.Fody/files/2441460/MethodBoundaryAspect.Fody.Issue.Repro.zip)

I would appreciate any feedback on any alternative or hint to implements the functionality that I am looking for. Thanks in advance!

On a side note: I am intrigued that the [MethodInterceptionAspect](http://doc.postsharp.net/t_postsharp_aspects_methodinterceptionaspect) has not yet had a similar implementation in Fody. Any thoughts on this would be welcome :)

**Comment by marcells** [comment]
Hi,

sorry for the late response. We currently have a lot of work to do. Do you think, that you could implement it and make a PR?

@Ralf1108 How complicated is it to implement this feature? Or do you have hints for @patrickcdsouza to make a PR?

**Comment by patrickcdsouza** [comment]
@marcells Thanks for the response :) . I am a newbie to Fody extension development and have started going through the MethodBoundaryAspect.Fody source. I could pick this up. As mentioned before any hints would be appreciated.

**Comment by Ralf1108** [comment]
PR #78  could solve the original issue as well. Feel free to verify this after merge is completed

**Comment by Ralf1108** [comment]
PR is merged.
Please try out the latest version 2.0.130 and close this issue if it is resolved

**Comment by Ralf1108** [comment]
I detected a limitation.
The values which are forwarded by ref wont be written back to the origin method. Only the weaved method will receive the ref arguments eventually modified in the aspect.
If this is required this has to be fixed separately.

**Comment by Ralf1108** [comment]
Also no async support yet. This has to be implemented as well.

**Comment by Ralf1108** [comment]
@patrickcdsouza your issue is now fixed.
With the latest MBA and your aspect annotated with the "AllowChangingInputArgumentsAttribute" all of your tests are now green.
