### ISSUE TITLE
Can you get the return type of a method?

### ISSUE THREAD

**Issue by jarrad-obrien** [vescon/MethodBoundaryAspect.Fody#51]
I'm trying to change the `ReturnValue` in `OnExit` for a method. I'm getting the value from a JSON file, so I need to cast it before I can set it as the `ReturnValue`. Is it possible to get the return type of the method?

For example: `arg.ReturnValue =(arg.Method.ReturnType).jsonFile["newValue"]`

**Comment by Ralf1108** [comment]
Please check the argument of the "OnExit" method.
It contains a property called "Method" of type MethodBase.
You try to cast this to a "MethodInfo" and then access its "ReturnType" property.

**Comment by Ralf1108** [comment]
A "MethodBase" object could be a "MethodInfo" or a "ConstructorInfo". The later one wont have a return type.

**Comment by Ralf1108** [comment]
[https://docs.microsoft.com/en-us/dotnet/api/system.reflection.methodbase?view=netframework-4.7.2](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.methodbase?view=netframework-4.7.2)
