### ISSUE TITLE
Simple Example for "MethodBoundaryAspect.Fody"

### ISSUE THREAD

**Issue by Brunhack** [vescon/MethodBoundaryAspect.Fody#52]
Hello

I try to implement the "MethodBoundaryAspect.Fody" but i cannot access to the abstract class "OnMethodBoundaryAspect". I don´t know why!
I think i initialize the "MethodBoundaryAspect.Fody" wrong :/

Is it possible to insert a MethodBoundaryAspect-Sample into this folder?
Would be nice! :)

**Comment by JamesFlames** [comment]
Maybe try changing the line which references MethodBoundaryAspect.Fody in
your references file to something like this
<PackageReference Include="MethodBoundaryAspect.Fody" Version="1.0.66" />
ie nothing about privateAssets etc.
That seemed to help me.

**Comment by JamesFlames** [comment]
So my suggestion didn't work?

**Comment by Brunhack** [comment]
Unfortunately yes. :/ 
I use the same version!

**Comment by marcells** [comment]
We are currently investigating the issue. We can reproduce it, but have no idea, why it doesn't work anymore. :-/

**Comment by Brunhack** [comment]
Thank you! ;)

**Comment by Martinay** [comment]
sample for netcore is fixed and added
