### ISSUE TITLE
MethodBoundaryAspect fails if assembly has a delegate

### ISSUE THREAD

**Issue by JamesFlames** [vescon/MethodBoundaryAspect.Fody#54]
MethodBoundaryAspect fails to weave some assemblies if the assembly has a delegate. A global assembly attribute is used to weave everything in an assembly. It fails saying the method has no body (meaning the delegate).
Here is a simple example.
https://github.com/JamesFlames/FailsToWeaveIfAssemblyHasDelegate/tree/master/FailsToWeave
I've added a pull request #55  that seems to fix this and also two tests one with an assembly which weaves and one with an assembly which fails to weave without the fix.

**Comment by Martinay** [comment]
#55
