### ISSUE TITLE
Watch variables while debugging an assembly. MethodName has "$_executor" prepended

### ISSUE THREAD

**Issue by JamesFlames** [vescon/MethodBoundaryAspect.Fody#56]
When debugging MethodBoundaryAspect weaved code I can't add variables to Visual Studio's Watch, but rather have to look at 'Locals' where the names anonymized to __var_0, __var_1, etc.
Is there anyway around this, to get the actual variables names or to use Visual Studio's watch and hover over variable value display in debug mode?

I'm using MethodBoundaryAspect Exception catching.  MethodBase.GetCurrentMethod().Name for a method called 'TestA' now returns "$_executor_TestA" instead of just 'TestA'. Is there a way to change this? Perhaps the aggressive inlining didn't inline it?

If it helps, in terms of weaving settings of some sort, here is an example of what the weaved code I get looks like.

WEAVEDCODE
  public class ListBasedHolidayBusinessLogic : IHolidayBusinessLogic
  {
    public List<LocalDate> Holidays;

    public ListBasedHolidayBusinessLogic(List<LocalDate> holidays)
    {
      this.Holidays = holidays;
    }

    [DebuggerStepThrough]
    public bool IsHoliday(string countryCode, string cityCode, LocalDate testDate)
    {
      object[] objArray = new object[3]
      {
        (object) countryCode,
        (object) cityCode,
        (object) testDate
      };
      MethodExecutionArgs methodExecutionArgs = new MethodExecutionArgs();
      methodExecutionArgs.set_Arguments(objArray);
      MethodBase currentMethod = MethodBase.GetCurrentMethod();
      methodExecutionArgs.set_Method(currentMethod);
      ListBasedHolidayBusinessLogic holidayBusinessLogic1 = this;
      methodExecutionArgs.set_Instance((object) holidayBusinessLogic1);
      ExceptionTrackerAspect exceptionTrackerAspect = new ExceptionTrackerAspect();
      ListBasedHolidayBusinessLogic holidayBusinessLogic2 = this;
      try
      {
        return holidayBusinessLogic2.\u0024_executor_IsHoliday(countryCode, cityCode, testDate);
      }
      catch (Exception ex)
      {
        Exception exception = ex;
        methodExecutionArgs.set_Exception(exception);
        exceptionTrackerAspect.OnException(methodExecutionArgs);
        if (methodExecutionArgs.get_FlowBehavior() != 1)
          throw ex;
        return (bool) methodExecutionArgs.get_ReturnValue();
      }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private bool \u0024_executor_IsHoliday(string countryCode, string cityCode, LocalDate testDate)
    {
      return this.Holidays != null && this.Holidays.Contains(testDate);
    }
  }

**Comment by Ralf1108** [comment]
Hi,
yes this is a known problem. Somehow the debug information is not correctly restored during weaving.
The weaving logic moves the method bodies into special method named "$_executor....." which is then called by the original method in addtion to the aspect methods.

Check method "Catel.Fody.CecilExtensions.UpdateDebugInfo()".

Maybe you have time to fix this by yourself and send us a PR?

**Comment by rualmar** [comment]
I saw that code was extracted from Catel.Fody repository, but the original code has changed since. Is it ok if I update it with the current code? I'll send a PR.

**Comment by rualmar** [comment]
I've sent a PR with the new code from the Catel.Fody repository. I've tested it with the HelloWorld solutions included here and now the debugger detects the names

**Comment by Martinay** [comment]
Thank you again for your pull request.
The issue should be fixed with version 2.0.109 . Please reopen this issue or create a new one, if the error still occures.

**Comment by rualmar** [comment]
Unfortunately, I've tested it on a full project and it keeps using the "__var_N" name on local variables, I don't know what are the differences between it and the test project. I'll keep testing and see if I can reach a good result and send a PR if I can solve it.

**Comment by runbyme** [comment]
@rualmar @Martinay @Ralf1108  Hi, have you got fix for that? I also facing same issue with strange local variables __var_0, __var_1, etc.
