### ISSUE TITLE
CS0103 while debugging on .NET Core 2.2

### ISSUE THREAD

**Issue by firatakyildiz** [vescon/MethodBoundaryAspect.Fody#62]
Hello,

After I upgraded my Web Api project from .Net Core 2.1 to 2.2, I can no longer see variables when debugging. I am getting "CS0103 : variable not defined in current context" errors. Although intellisense recognizes and autocompletes variable names in Immediate Window, it says variable not defined there either. Removing the attribute fixes the problem. 

Note that this problem is caused when my attribute has classes as target. I have another attribute targeting methods and it does not create issues for me.

You can find a minimal project with issue here : 
https://github.com/firatakyildiz/MethodBoundaryAspectBug

You can put a brekapoint at Domain.Operation.SampleMethod and see the issue.

Thanks in advance

**Comment by Ralf1108** [comment]
Yes we currently have problems fixing th debug information to match the weaved il code.
Unfortunately I dont know if we can fix this easily

**Comment by runbyme** [comment]
@firatakyildiz @Ralf1108 I have same issue on .NET Framework. Do you have solution for that? I also see only __var_0, __var_1 etc. variables while debugging in Visual Studio :/

**Comment by firatakyildiz** [comment]
@runbyme Nope, have no idea.

**Comment by runbyme** [comment]
> @runbyme Nope, have no idea.

So it works for you when you have `[AttributeUsage(AttributeTargets.Method)]` attribute on aspect? Becouse for me it doesn't work either.

**Comment by ddalalrms** [comment]
We are having issues with local variables invisible at Debug time ... when will this be fixed you think?

**Comment by Martinay** [comment]
can you please retry this with version 2.0.139
there was a similar issue #71 which is fixed now

**Comment by Murphybro2** [comment]
> can you please retry this with version 2.0.139
> there was a similar issue #71 which is fixed now

I just updated and can confirm it appears to be working okay now!

**Comment by Martinay** [comment]
Thanks for verifying this. If the error occurs again please reopen or create a new bug.
