### ISSUE TITLE
Integration with Polly to implement retry operations

### ISSUE THREAD

**Issue by nicolastakashi** [vescon/MethodBoundaryAspect.Fody#65]
Hello everyone!

I've made search in issues and other places like StackOverflow and Google and I could't find nothing about that.

I want to create a attribute to implemente resilient operations, using [Polly], but I have a lot of doubts and I don't found way to make this implementation.

Looking to [Postsharp Method Interception] documentation, we can see a way to know when our method is invoked and intercept.

Exists some thing like that inside Fody MethodBoundary?

Using PostSharp we can make something like that:

```
public class RetryOnExceptionAttribute : MethodInterceptionAspect
{
     public RetryOnExceptionAttribute()
     {
        this.MaxRetries = 3;
     }

     public int MaxRetries { get; set; }

     public override void OnInvoke(MethodInterceptionArgs args)
     {
        Policy
            .Handle<SomeExceptionType>()
            .Retry(MaxRetries, onRetry: (exception, retryCount) =>
            {
                    // do something 
            }).Execute(args.Proceed);
        }
}
```

[Polly]:<https://github.com/App-vNext/Polly>
[Postsharp Method Interception]:<https://doc.postsharp.net/method-interception>

My apologies if I made mistakes

**Comment by Ralf1108** [comment]
Hi, sorry for late answer.

Unfortunately what ou want to do is not possible with MBA.
What you want to implmement is a "MethodInterceptionAspect" where you have control over the method invocation like Retry or Skipping the invocation at all.

MBA is only a MethodBoundaryAspect which means you can inject code into the boundaries of a method invocation like OnEntry or OnExit. It is not possible to alter the invocation of the method there.
This would require a new Fody weaver.


For comparison check out PostSharps aspect: [MethodInterceptionAspect](https://doc.postsharp.net/method-interception)
