### ISSUE TITLE
Build fails when using Fody 6.0 and adding attribute to method invoking static method 

### ISSUE THREAD

**Issue by robertocpsilva1** [vescon/MethodBoundaryAspect.Fody#67]
This works on 5.2.0 but fails on 6.0

The code is pretty simple, just calling a static method on a 3rd party library (SpreadsheetGear)

```
[MyAttribute]
private IWorkbook GetWorkbookFromMemory(byte[] buffer)
{
    return Factory.GetWorkbookSet().Workbooks.OpenFromMemory(buffer);
}
```

```
7>MSBUILD : warning FodyVersionMismatch: Fody: Weavers should reference at least the current major version of Fody (version 6). The weaver in MethodBoundaryAspect.Fody references version 3. This may result in incompatibilities at build time such as MissingMethodException being thrown.
7>MSBUILD : error : Fody: Failed to execute weaver C:\Users\silvro\.nuget\packages\methodboundaryaspect.fody\2.0.113\build\..\netclassicweaver\MethodBoundaryAspect.Fody.dll due to a MissingMemberException. Message: Method not found: 'Mono.Collections.Generic.Collection`1<Mono.Cecil.TypeReference> Mono.Cecil.GenericParameter.get_Constraints()'.. This is likely due to the weaver referencing an old version (3) of Fody.
```

Not that I need or even know what the features are but thought I'd raise it.
Does it just need updated to 6.0?

**Comment by Martinay** [comment]
It looks like fody added a check of the addins version ([commit](https://github.com/Fody/Fody/commit/76a7bc9c4bd6b7aa1643ebafbc110c735f9b37b9)) .

Fody added from version 3.3.3 and upwards an [Licensing/Patron FAQ ](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md)and expects consumers of the library to pay. On the other side it still has the MIT license. 
It's said in the faq 

> 
> What about open source projects consume or producing Fody weavers?
> 
> It is be expected that the core team of maintainers of any open source projects that consume or produce Fody weavers would become Patrons. Non core contributors do not need to become Patrons. For example, in the context of GitHub, this would be any people with push access to the the repository. The reasoning is that if a project is utilizing Fody, that should not be a blocker for the larger community from contributing to the project.

I think we need to discuss how to handle it and if we upgrade the dependency to the latest version

**Comment by AlexVPerl** [comment]
I'm also facing this issue with Fody 6.0+. Builds fine with Fody 5.2 without problems though.

I see that the referenced commit by @Martinay has:
`ValidateWeaverReferencesAtLeastTheCurrentMajorOfFody`

But that just seems that MethodBoundaryAspect needs to be updated to reference 6.+ or am I wrong?

Also, a bit confused by mention of patron expectation - does that somehow prevent the build using Fody 6.+ ?

Would be great to update to latest Fody version.

Thanks in advance.

**Comment by tom-englert** [comment]
Fody 6.x includes a newer version of Mono.Cecil, which is required to gurantee lossles transformation of the IL-code. This version of Mono.Cecil is not 100% backward compatible, thats why you get the MissingMethodException.
