### ISSUE TITLE
__var_0, __var_1... while debugging in Visual Studio

### ISSUE THREAD

**Issue by runbyme** [vescon/MethodBoundaryAspect.Fody#71]
I see that this issue still exists: https://github.com/vescon/MethodBoundaryAspect.Fody/issues/56
While debugging in Visual Studio local variables are swaped to __var_0, __var_1 (.NET Framework, aspect on method)

**Comment by jmartschinke** [comment]
![image](https://user-images.githubusercontent.com/79451982/108699759-f58ee100-7505-11eb-95e4-b2a620679c7e.png)

Issue still persists as of current v2.0.138

**Comment by jmartschinke** [comment]
Pull Request opened on https://github.com/vescon/MethodBoundaryAspect.Fody/pull/80

**Comment by Martinay** [comment]
fixed in 2.0.139
thanks again for your pull request
