### ISSUE TITLE
Is there a reason DisableWeaver can only applied to methods and not classes?

### ISSUE THREAD

**Issue by kampilan** [vescon/MethodBoundaryAspect.Fody#73]
I am using this addin to implement automatic logging with my logging framework. When adding the automatic logging at first the attribute is applied on the assembly(ies). As more detailed manual logging is added to a particular class, I would like to mark that class with DisableWeaver. Is there anything that prevents DisableWeaver from being applied to a class other then its AttributeUsage does not allow it? If  Class was added to the AttributeUsage should it work?

Thanks
Jim

**Comment by Ralf1108** [comment]
It was only used for disabling weaving for some methods.
But if you want to support also classes check class [ModuleWeaver](https://github.com/vescon/MethodBoundaryAspect.Fody/blob/1ea8b480935ca824639254798acc4aa597e7f33b/src/MethodBoundaryAspect.Fody/ModuleWeaver.cs) and the method "IsIgnoredByWeaving".
If you would extend this we like to accept your PR :-)

**Comment by Ralf1108** [comment]
you can now annotate classes and assemblies withe the `DisableWeavingAttribute` to disable weaving.
Requires MBA version 2.0.138
