### ISSUE TITLE
Is it possible to make the Arguments be updated?

### ISSUE THREAD

**Issue by Oceania2018** [vescon/MethodBoundaryAspect.Fody#77]
@Ralf1108 @marcells 
Thanks for this great library.
I want to use this library to implement `AutoGraph` feature in my [TensorFlow.NET](https://github.com/SciSharp/TensorFlow.NET) repo.
Most of the things are working perfectly, there is only one thing doesn't meet the my situation. I need to change the arguments before method is executed.

I use ILSpy to check the generated code:
Original Code:
```csharp
        [AutoGraphAspect]
        Tensor Add(Tensor a, Tensor b)
        {
            return a + b;
        }
```

Generated Code:
```csharp
[AutoGraphAspect]
[DebuggerStepThrough]
private Tensor Add(Tensor a, Tensor b)
{
	object[] __var_11 = new object[2]
	{
		a,
		b
	};
	MethodExecutionArgs __var_10 = new MethodExecutionArgs();
	__var_10.Arguments = __var_11;
	System.Reflection.MethodBase __var_9 = __var_10.Method = System.Reflection.MethodBase.GetCurrentMethod();
	FunctionApiTest __var_8 = (FunctionApiTest)(__var_10.Instance = this);
	AutoGraphAspect __var_7 = new AutoGraphAspect();
	__var_7.OnEntry(__var_10);
	FlowBehavior __var_6 = __var_10.FlowBehavior;
	if (__var_6 == FlowBehavior.Return)
	{
		return (Tensor)__var_10.ReturnValue;
	}
	Tensor __var_5 = (Tensor)(__var_10.ReturnValue = this.$_executor_Add(a, b));
	__var_7.OnExit(__var_10);
	return (Tensor)__var_10.ReturnValue;
}

```
What I need is like below:

![image](https://user-images.githubusercontent.com/1705364/94073418-10292680-fdbd-11ea-87e2-d0c138c7baa0.png)

**Comment by Ralf1108** [comment]
Interesting requirement. This would match that we allow changing the return in the aspect so why not also modify the input arguments.
I will look into this

**Comment by Ralf1108** [comment]
see PR #78

**Comment by Ralf1108** [comment]
PR is merged.
Please try out the latest version 2.0.130 and close this issue if it is resolved

**Comment by Ralf1108** [comment]
I detected a limitation.
The values which are forwarded by ref wont be written back to the origin method.
If this is required this has to be fixed separately.

**Comment by Ralf1108** [comment]
Also no async support yet. This has to be implemented as well.

**Comment by Oceania2018** [comment]
Still doesn't work. I upgrade to `2.0.133` version.

![image](https://user-images.githubusercontent.com/1705364/94583386-ff583500-0242-11eb-854f-80d9bbc14107.png)

**Comment by Ralf1108** [comment]
I fixed the copy back step for ByRef arguments to the caller. But this should not affect your sample.

Please try out the sample on the main page with MBA version at least 2.0.134

```csharp
using System;
using MethodBoundaryAspect.Fody.Attributes;

[AllowChangingInputArguments]
public sealed class InputArgumentIncrementorAttribute : OnMethodBoundaryAspect
{
    public int Increment { get; set; }

    public override void OnEntry(MethodExecutionArgs args)
    {
        var inputArguments = args.Arguments;
        for (var i = 0; i < inputArguments.Length; i++)
        {
            var value = inputArguments[i];
            if (value is int v)
                inputArguments[i] = v + Increment;
        }
    }
}

public class Program
{
    public static void Main(string[] args)
    {
        // ByValue
        MethodByValue(10);

        // ByRef
        var value = 10;
        MethodByRef(ref value);
        Console.WriteLine("after method call: " + value); // Output: 20
    }

    [InputArgumentIncrementor(Increment = 1)]
    public static void MethodByValue(int i)
    {
        Console.WriteLine(i); // Output: 11
    }

    [InputArgumentIncrementor(Increment = 10)]
    public static void MethodByRef(ref int i)
    {
        Console.WriteLine(i); // Output: 20
    }
}
```

**Comment by Oceania2018** [comment]
@Ralf1108 It works now. Appreciate for your work.
