### ISSUE TITLE
Conditional statement replacement

### ISSUE THREAD

**Issue by Oceania2018** [vescon/MethodBoundaryAspect.Fody#79]
Hi @Ralf1108 , the `AllowChangingInputArguments` works very well. Appreciate for your great help.
Now another more challenge task come up:

Original code:
```csharp
Tensor Min(Tensor a, Tensor b)
{
   return a < b ? a : b;
}
```

Parsed code I need:
```csharp
Tensor Min(Tensor a, Tensor b)
{
    return tf.cond(a < b, () => a, () => b);
}
```
For simplicity, can we use `MethodBoundaryAspect.Fody` to replace `a < b ? a : b` to `tf.cond(a < b, () => a, () => b)` ?

**Comment by Ralf1108** [comment]
Hi @Oceania2018,

unfortunatly your requirement would require to implement a whole new fody weaver.
The MBA doesn't change the method bodies of the  original methods. It just encapsulate the original method call to intercept the start and end.

So unfortunatley MBA would be no help there for you.
