### ISSUE TITLE
Overriding OnException without overriding OnEntry results in a NullReferenceException

### ISSUE THREAD

**Issue by pdohogne** [vescon/MethodBoundaryAspect.Fody#8]
Decompiled generated code looks like

```
catch (Exception ex)
     {
       methodExecution.Exception = ex;
       TestAttribute testAttribute;
       testAttribute.OnException(methodExecution);
       throw;
     }
```

**Comment by SparkRooster** [comment]
I have an attribute only overriding OnException and I do not get this error, either in Debug or Release

**Comment by Ralf1108** [comment]
Seems to be already fixed.

Output of test : "IfMethodWithAspectOnExceptionOnlyIsWeaved_ThenTheAssemblyShouldBeValid" is:

![grafik](https://user-images.githubusercontent.com/3949137/34303323-1def171c-e735-11e7-81b7-f53539527cef.png)
